import Head from 'next/head';
import { useEffect, useContext, useState } from 'react';
import { AuthContext } from '@context/AuthContext'; // Importamos el contexto de autenticación
import { useRouter } from 'next/router';

export default function Home() {
  const { state } = useContext(AuthContext); // Accedemos al contexto
  const router = useRouter();

  useEffect(() => {
    // Verificamos si no hay token en el contexto
    if (!state?.token) {
      router.push('/Login'); // Redirigimos al login si no hay token
    }
  }, [state?.token, router]);

  return (
    <>
      <Head>
        <title>Test Inventory - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {state?.token && ( // Solo mostramos contenido si hay token
        <>
          <h1>Bienvenido</h1>
          <p>Esto es la página principal.</p>
        </>
      )}
    </>
  );
}
